import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header from "@/components/Header";
import { Toaster } from "react-hot-toast";

import { InquiriesProvider } from "@/context/inquiries-context";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Kanban Board",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`font-poppins antialiased bg-600`}>
        <InquiriesProvider>
          <Header />
          <main className="max-w-[1320px] w-full px-5 m-auto min-h-screen mt-8 mb-8">
            {children}
          </main>
          <Toaster />
        </InquiriesProvider>
      </body>
    </html>
  );
}
